# railway.toml

# Versi konfigurasi Railway
version = 2

# Tentukan layanan atau kontainer
[[services]]
  name = "rasa-server"
  image = "railwayapp/python:3.7.7"
  env = ["PYTHONPATH=/app"]
  ports = ["5006:5006", "8080:8080"]
  disk = 256
  command = "bash -c 'pip install rasa && rasa run'"
