# railway.toml

# Tentukan versi Railway configuration
version = 2

# Tentukan layanan atau kontainer
[[services]]
  name = "rasa-server"
  image = "railwayapp/python:3.7.7"
  env = ["PYTHONPATH=/app"]
  ports = ["5006:5006", "8080:8080"]
  disk = 256
